spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Jktu310590#

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.ddl-auto: validate
    show-sql: true
